// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chatbot.Data;

namespace chatbot.Migrations.ChatInfo
{
    [DbContext(typeof(ChatInfoContext))]
    [Migration("20201214152203_ChatInfo")]
    partial class ChatInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("chatbot.Models.Allusers", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("allusers");
                });

            modelBuilder.Entity("chatbot.Models.Chatinfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("DisabledCommands")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("disabled_commands");

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rules");

                    b.Property<int?>("WarnsQuantity")
                        .HasColumnType("int")
                        .HasColumnName("warns_quantity");

                    b.Property<string>("Welcome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("welcome");

                    b.HasKey("Id");

                    b.ToTable("chatinfo");
                });

            modelBuilder.Entity("chatbot.Models.Users", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("Chatid")
                        .HasColumnType("bigint")
                        .HasColumnName("chatid");

                    b.Property<long?>("Userid")
                        .HasColumnType("bigint")
                        .HasColumnName("userid");

                    b.Property<int?>("Warns")
                        .HasColumnType("int")
                        .HasColumnName("warns");

                    b.HasKey("Id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
